export const macos = {
  name: 'macos',
  lines: [
    '       .--.        ',
    '     /  .  \\       ',
    '    /  / \\  \\      ',
    '   /  /   \\  \\     ',
    '  /  /---- \\  \\    ',
    ' /  /      \\  \\   ',
    ' \\  \\      /  /   ',
    '  \\  \\----/  /    ',
    '   \\  \\  /  /     ',
    '    \\  \\/  /      ',
    '     \\    /       ',
    '      `--`        ',
    '   macOS Apple    ',
  ],
  colors: [
    'green',
    'green',
    'yellow',
    'yellow',
    'red',
    'red',
    'magenta',
    'magenta',
    'blue',
    'blue',
    'cyan',
    'cyan',
    'white',
    'white',
    'white',
    'white',
  ],
};

export default macos;
