export const windows = {
  name: 'windows',
  lines: [
    '  ____________      ',
    ' |            |     ',
    ' |   .----.   |     ',
    ' |   |    |   |     ',
    ' |   |    |   |     ',
    ' |   `----`   |     ',
    ' |------------|     ',
    ' |   .----.   |     ',
    ' |   |    |   |     ',
    ' |   |    |   |     ',
    ' |   `----`   |     ',
    ' |____________|     ',
    '                    ',
    '   Windows Pane     ',
    '  .-----------.     ',
    '  `-----------`     ',
  ],
  colors: [
    'blue',
    'blue',
    'red',
    'red',
    'red',
    'red',
    'white',
    'green',
    'green',
    'green',
    'green',
    'yellow',
    'white',
    'cyan',
    'white',
    'white',
  ],
};

export default windows;
